"""LangGraph assembly for the 3-role trading system.

Builds a debate+judge graph: Bull ↔ Bear → Judge
Research report is already generated by individual section calls.
"""

from langgraph.graph import StateGraph, END, START

from backend.graph.agent_state import AgentState
from backend.graph.conditional_logic import ConditionalLogic
from backend.agents.bull_agent import create_bull_agent
from backend.agents.bear_agent import create_bear_agent
from backend.agents.judge_agent import create_judge_agent


def build_debate_judge_graph(
    deep_llm,       # For the Judge (structured output)
    quick_llm,      # For Bull + Bear
    max_debate_rounds: int = 1,
):
    """Build a debate+judge-only graph (no DataCollector).

    Used in on-demand mode where research sections are generated
    individually before debate is triggered.
    """
    conditional_logic = ConditionalLogic(max_debate_rounds=max_debate_rounds)

    bull = create_bull_agent(quick_llm)
    bear = create_bear_agent(quick_llm)
    judge = create_judge_agent(deep_llm)

    workflow = StateGraph(AgentState)

    workflow.add_node("BullAgent", bull)
    workflow.add_node("BearAgent", bear)
    workflow.add_node("JudgeAgent", judge)

    # Start directly with BullAgent (research report is already in state)
    workflow.add_edge(START, "BullAgent")

    workflow.add_conditional_edges(
        "BullAgent",
        conditional_logic.after_bull,
        {"BearAgent": "BearAgent", "JudgeAgent": "JudgeAgent"}
    )

    workflow.add_conditional_edges(
        "BearAgent",
        conditional_logic.after_bear,
        {"BullAgent": "BullAgent", "JudgeAgent": "JudgeAgent"}
    )

    workflow.add_edge("JudgeAgent", END)

    return workflow.compile()
